// Display labels for the facet slugs in a support line's `helpsWith` /
// `targetGroups`.
//
// Those fields are ascii-folded slugs ("sjalvmordstankar", "rad-och-stod") —
// good for ids, URLs and search matching, wrong for anything a reader sees.
// FACET_LABEL is the curated slug → Swedish label map; `facetLabel()` falls
// back to a de-slugified guess so a new value still renders sensibly (it just
// won't get its å/ä/ö until it's added here).
//
// Keep the slugs as they are — they are the internal keys. Only the right-hand
// side is display text.

const FACET_LABEL: Record<string, string> = {
  adhd: "ADHD",
  akeriforetagare: "Åkeriföretagare",
  "akuta-atgarder": "Akuta åtgärder",
  aldre: "Äldre",
  "alla-aldrar": "Alla åldrar",
  "alla-konsidentiteter": "Alla könsidentiteter",
  allmanheten: "Allmänheten",
  andts: "ANDTS",
  angest: "Ångest",
  "anhorig-till-alkoholist": "Anhörig till alkoholist",
  "anhorig-till-brottsutsatt": "Anhörig till brottsutsatt",
  anhoriga: "Anhöriga",
  anhorigskap: "Anhörigskap",
  anhorigstod: "Anhörigstöd",
  anmalan: "Anmälan",
  atstorningar: "Ätstörningar",
  "barns-psykiska-halsa": "Barns psykiska hälsa",
  "barns-rattigheter": "Barns rättigheter",
  "beroendeframkallande-lakemedel": "Beroendeframkallande läkemedel",
  brottsforebyggande: "Brottsförebyggande",
  "cis-killar": "Ciskillar",
  droganvandning: "Droganvändning",
  efterlevandestod: "Efterlevandestöd",
  "enskilda-stodsamtal": "Enskilda stödsamtal",
  "existentiella-fragor": "Existentiella frågor",
  familjestod: "Familjestöd",
  fjallraddning: "Fjällräddning",
  folkhalsa: "Folkhälsa",
  foraldrar: "Föräldrar",
  foraldraskap: "Föräldraskap",
  "forandring-av-alkoholvanor": "Förändring av alkoholvanor",
  "forandring-av-drogvanor": "Förändring av drogvanor",
  forgiftning: "Förgiftning",
  "forlust-av-barn": "Förlust av barn",
  "forlust-av-narstaende": "Förlust av närstående",
  "fragor-till-roda-korset": "Frågor till Röda Korset",
  gad: "GAD",
  "hbtqia-fragor": "HBTQIA-frågor",
  "hbtqia-personer": "HBTQIA-personer",
  "hbtqia-stod": "HBTQIA-stöd",
  "hitta-mote": "Hitta möte",
  "hitta-vard": "Hitta vård",
  "hjalp-vidare-till-behandling": "Hjälp vidare till behandling",
  hopploshet: "Hopplöshet",
  "hot-och-vald": "Hot och våld",
  ickebinara: "Ickebinära",
  "journal-och-vardtjanster": "Journal och vårdtjänster",
  "juridisk-vagledning": "Juridisk vägledning",
  "juridiska-fragor": "Juridiska frågor",
  kamratstod: "Kamratstöd",
  "killar-10-25": "Killar 10–25 år",
  "konsbekraftande-vard": "Könsbekräftande vård",
  konsdysfori: "Könsdysfori",
  konsidentitet: "Könsidentitet",
  krankningar: "Kränkningar",
  "krisstod-och-humanitart-stod": "Krisstöd och humanitärt stöd",
  kunskapsstod: "Kunskapsstöd",
  lakemedel: "Läkemedel",
  lastbilsforare: "Lastbilsförare",
  livsfragor: "Livsfrågor",
  "lokalt-stod": "Lokalt stöd",
  maende: "Mående",
  man: "Män",
  "misstankt-forgiftning": "Misstänkt förgiftning",
  "motivation-till-forandring": "Motivation till förändring",
  nedstamdhet: "Nedstämdhet",
  "npf-fragor": "NPF-frågor",
  "oro-for-att-skada-andra": "Oro för att skada andra",
  "oro-for-barn": "Oro för barn",
  "oro-for-kropp-mat-och-traning": "Oro för kropp, mat och träning",
  "oro-for-mat-kropp-och-traning": "Oro för mat, kropp och träning",
  "oro-for-nagon-annan": "Oro för någon annan",
  "oro-for-nagon-annans-spelande": "Oro för någon annans spelande",
  "oro-for-narstaende": "Oro för närstående",
  overlevare: "Överlevare",
  "oönskad-sexualitet": "Oönskad sexualitet",
  panikangest: "Panikångest",
  "personer-fran-12-ar": "Personer från 12 år",
  "personer-i-akut-nod": "Personer i akut nöd",
  "personer-med-angest": "Personer med ångest",
  "personer-med-atstorningsproblematik": "Personer med ätstörningsproblematik",
  "personer-med-npf": "Personer med NPF",
  "personer-med-oonskad-sexualitet": "Personer med oönskad sexualitet",
  "personer-med-utlandsk-bakgrund": "Personer med utländsk bakgrund",
  "personer-som-anvander-droger": "Personer som använder droger",
  "personer-som-funderar-pa-konsidentitet": "Personer som funderar på könsidentitet",
  "personer-som-funderar-pa-sexualitet": "Personer som funderar på sexualitet",
  "praktisk-vagledning": "Praktisk vägledning",
  "praktiskt-stod": "Praktiskt stöd",
  "professionell-vagledning": "Professionell vägledning",
  "psykisk-ohalsa": "Psykisk ohälsa",
  "psykiskt-daligt-maende": "Psykiskt dåligt mående",
  "psykiskt-maende": "Psykiskt mående",
  "rad-och-stod": "Råd och stöd",
  raddningstjanst: "Räddningstjänst",
  radgivning: "Rådgivning",
  "radgivning-for-yrkesverksamma": "Rådgivning för yrkesverksamma",
  "ran-eller-overfall": "Rån eller överfall",
  rattigheter: "Rättigheter",
  rattighetsinformation: "Rättighetsinformation",
  rattsprocessen: "Rättsprocessen",
  samtalsstod: "Samtalsstöd",
  "sexuella-overgrepp": "Sexuella övergrepp",
  "sexuellt-vald": "Sexuellt våld",
  sjalvbild: "Självbild",
  sjalvhjalp: "Självhjälp",
  sjalvhjalpsmoten: "Självhjälpsmöten",
  sjalvmordstankar: "Självmordstankar",
  sjalvskadebeteende: "Självskadebeteende",
  sjoraeddning: "Sjöräddning",
  sjukvardsradgivning: "Sjukvårdsrådgivning",
  socialtjanst: "Socialtjänst",
  "stod-for-hbtqi-personer": "Stöd för HBTQI-personer",
  "stod-for-narstaende": "Stöd för närstående",
  "stod-fran-andra-med-erfarenhet": "Stöd från andra med erfarenhet",
  "stod-och-rad": "Stöd och råd",
  "stod-och-radgivning": "Stöd och rådgivning",
  "stod-till-samer": "Stöd till samer",
  "stod-till-unga": "Stöd till unga",
  stodgrupp: "Stödgrupp",
  stodnatverk: "Stödnätverk",
  stodpersoner: "Stödpersoner",
  "svar-livssituation": "Svår livssituation",
  "svarkris-i-arbetet": "Svår kris i arbetet",
  tillganglighet: "Tillgänglighet",
  tjanstgorande: "Tjänstgörande",
  "tjejer-10-25": "Tjejer 10–25 år",
  "trans-killar": "Transkillar",
  transfragor: "Transfrågor",
  "trygga-motesplatser": "Trygga mötesplatser",
  trygghetsfragor: "Trygghetsfrågor",
  "unga-12-25": "Unga 12–25 år",
  "unga-16-25": "Unga 16–25 år",
  "unga-hbtqia-personer": "Unga HBTQIA-personer",
  "unga-med-npf": "Unga med NPF",
  "unga-under-18": "Unga under 18 år",
  "unga-upp-till-25": "Unga upp till 25 år",
  "unga-upp-till-30": "Unga upp till 30 år",
  utlandstjanst: "Utlandstjänst",
  "utsatt-for-brott": "Utsatt för brott",
  "utsatta-fran-13-ar": "Utsatta från 13 år",
  vagledning: "Vägledning",
  "vagledning-till-stod": "Vägledning till stöd",
  vald: "Våld",
  "vald-i-nara-relation": "Våld i nära relation",
  "vald-och-krankningar": "Våld och kränkningar",
  valdsutovare: "Våldsutövare",
  valdsutsatta: "Våldsutsatta",
  valdtakt: "Våldtäkt",
  vanner: "Vänner",
  "vard-och-omsorg": "Vård och omsorg",
  vardagsstod: "Vardagsstöd",
  vardgivare: "Vårdgivare",
  vardniva: "Vårdnivå",
  vardpersonal: "Vårdpersonal",
  "veteran-och-anhorigstod": "Veteran- och anhörigstöd",
  "voldsamt-beteende": "Våldsamt beteende",
  "vuxna-over-18": "Vuxna över 18 år",
};

/** Reader-facing label for a facet slug. */
export function facetLabel(slug: string): string {
  return (
    FACET_LABEL[slug] ??
    slug.replace(/-/g, " ").replace(/^./, (c) => c.toUpperCase())
  );
}
